version: '3.3'

services:
  app:
    build:
      context: .
    environment:
      VIRTUAL_HOST: user-referal.dev
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - .:/var/www/html:delegated
    network_mode: bridge
    restart: always
